GET http://localhost:8080/devops_starter_war_exploded/api/employee/getAll

###
POST http://localhost:8080/devops_starter_war_exploded/api/employee
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"name": "Hassan", "address": "Kronborg 6"}